= BPMD - **BPM**N **D**SL (link:https://hans-giebenrath.github.io/bpmd-antora/bpmd/index.html[Standalone Docs])
:toc:

Create BPMN diagrams from text files. Similar to Mermaid/PlantUML/... but for BPMN. Primarily targeting .svg, but a less tested .bpmn (i.e. XML) export is present as well.

*This project is in an early development stage and is missing features which are required for serious usage.*

BPMD is a tool which takes as input a text file in the BPMD format (`.bpmd`) and outputs a layouted BPMN diagram (`.svg` or `.bpmn`).
The goal is to enable the author of a diagram to focus on the semantics of a diagram.
However, when creating a diagram by moving boxes and arrows, the author needs to focus at the same time on the presentation.
Simply put, this tool determines the `x`, `y`, `width` and `height` values of all the elements in your diagram, you just describe your process.

The *hope* is that this allows for:

* Consistent layouts (e.g. equal margins within a diagram and across diagrams).
* Faster diagram sketching, and faster modification of an existing diagram (like inserting a box in
  the middle of the diagram).
* Creation of diagrams which are *good enough* for regular purposes, so you never need to
  post-process any of the diagrams except for exceptional situations with higher aesthetic
  requirements.
* An overall pleasant diagram creation experience for fans of Mermaid/PlantUML/...
* Simple enough language that can be mastered also by non-programmers.

At the very least it should make the initial process design phase quicker, and when the rough pillars are in place you can take the layouted image as a template when you finalize the diagram in a visual tool.

```bpmd
= This is a Pool
== This is a Lane

# Start Event
X I am an exclusive Gateway
  ->one-branch"Let's Go here"
  ->the-other-branch"No, here!"

- Wonderful Task <-one-branch ->we-are-done

- Share a Message <-the-other-branch ->we-are-done

X <-we-are-done
. Context Switch

= Another Pool Begins

# We got an Inspiration
- Think
 T! ->later
. Epiphany

. No Epiphany Today <-later

// Message Flow
MF <-share ->inspiration
```

image::test/readme01.svg[]

== Why could this be useful?

This tool tries to fall into the same niche as PlantUML and similar tools. The target group is (probably) primarily users which are home in text files. A couple of (subjective) benefits:

* Author can focus on content rather than Layout - an okayish layout is calculated automatically
* Later changes to the process, like adding a task activity somewhere in the middle, don't require a full (manual) rework of the surrounding layout.
* Better integration with version control systems:
  * The syntax aims to split the process description from layout tweaks. Meaning that a diffs are more meaningful (one can rather concentrate on the changes of the process than on layout peculiarities)
* Any advantage which text files bring over binary files (like one can stay within one's beloved text editor / IDE to code, document and create diagrams without mouse interruptions)

[[missing-pieces]]
== Missing Pieces

Layout (probably not a good first issue):

* Bug fixes (see separate TODO file)
* Gateway *happy path* marking (though this might fall into the layout-instructions section): right
  now the gateway nodes are balanced between outgoing edges. But sometimes one outgoing edge is the
  *happy path* and this should go straight out. Non-happy path edges lead to tasks to handle
  exceptional situations, so they should branch out off sight (harshly spoken).
* Marking a pool as black box (or hiding them altogether)
* Nested states
* Separate Interrupt States
* Make data nodes in half-layers more integrated (force message flow endpoint nodes into other
  layers if they would otherwise go through a half layer with a data node, similar mechanism for
  when the message flow ends in the same lane, to ensure the crossing minimization phase accounts
  for that)
* Label positioning in the xml export (only manually done in svg export right now).
* Data nodes and gateways cannot be connected.

Non-Layout (good for contributors):

* SVG-Based Image Export (in addition to XML export)
* Interactive SVG Export (hovering over a data object highlights the full data traversal path, etc)
* LSP/treesitter/...
* `import` statement (this is a bit tricky actually)
* Parsing of config values from the `.bpmd` files
* A collaborative online editor (ideally with WASM compiled BPMD tool, using `microlp`).

== Goals

* Layouts should be *good enough* for everyday use to not warrant manual corrections in like 90% of
  the cases.

== Non-Goals

* Make 100% aesthetically perfect diagrams. This is subjective and depends on the human who looks at
  the diagram. In that regard I deem it impossible to achieve a *perfect* diagram layout.
* Support of *grouping*. This is just not compatible with the layout algorithm being employed.
  Groups can stretch across lanes and pools, but the algorithm is primarily lane-focused with just
  some inter-lane and inter-pool extensions. That is to say, I think one could achieve grouping for
  simple use cases, but better just use colors to denote that some nodes are semantically related.
  So I think that, unless someone points me to a fun algorithm to make it work for non-trivial cases
  (multiple nodes, across lanes and pools), grouping will not happen.

== Project State

The BPMD tool is in an alpha stage.
Lot's of stuff is working already to make some useful diagrams, but many must-have features <<missing-pieces,are missing>> or are a little bit broken.

At the moment, this is my personal hobby project (but refer to the <<project-history,history>> section for the more vivid project beginnings).
I enjoy working on the project since it seems like a similar tool does not exist, yet (i.e. I can make an actual impact with this tool. To the best of my knowledge this project is "not just another toaster"), and since it is nostalgic for me (applying the Sugiyama framework was my bachelor's thesis, good old university days).
But I do have other things to work on, especially during the warmer months there is wood working to do, and this will very likely result in a slower pace.
That said, there are no guarantees for any non-implemented features to ever land, nor for any present bugs to ever be fixed.
It is purely my hobby at this moment, and I try to not get burned out on it as I really do like it.
This means that sometimes I need to take a break and read a book instead for a couple of days or weeks, to return with fresh energy.

== AI Usage Within This Project

I can only speak for the code I wrote myself:
This project is not vibe coded.
For the layout algorithm, I scribbled tens (not yet hundreds) of sheets of paper with examples and edge cases to work out algorithms.
Really, a lot of thinking was done for this project by all contributors.

That said, I use ChatGPT Plus from time to time (the bog standard web interface). Some examples of usages:

* Helping with Rust iterator puzzles
* Give ideas to simplify unreadable functions
* Help with naming stuff (e.g. double checking that `LayoutConstraint` is a good name)
* Create me an ILP for the global edge crossing minimization (I ended up reading the existing literature instead)

== Installation

Refer to link:https://hans-giebenrath.github.io/bpmd-antora/bpmd/install.html[this page] for installation instructions.

== DSL Syntax Overview

The syntax is explained link:https://hans-giebenrath.github.io/bpmd-antora/bpmd/dsl-overview.html[here].

== PE-BPMD

My interpretation of the PE-BPMN extension, explained link:https://hans-giebenrath.github.io/bpmd-antora/bpmd/pe-bpmd/introduction.html[here].

== Building The Test Images

This might give you a good reference of what I in general want to support, even if the results might not be good at the moment.

```bash
cd test
npm install # for bpmn-to-image

# Run on your own responsibility. Sometimes there is a endless loop when I do some tweaks and it breaks
# an edge case and I forget to run this command again.
./build.sh

# Or just a single image
BDT=t0001.bpmd ./build.sh
```

[[project-history]]
== Project History

I wrote my bachelor's thesis back in 2015/2016 on the topic of implementing (and enhancing) a layout algorithm for Matlab/Simulink diagrams.
There I learned about and applied the Sugiyama framework for hierarchical graph drawing.
Fast forward many years, and at my then-$dayjob at link:cyber.ee[Cybernetica] we were creating BPMN diagrams.
That said, I did not because whenever I tried to create one, I was reminded of my bachelor's thesis and thinking that this must be layoutable by a computer, given some custom DSL similar to how Plantuml/Mermaid/... are working.
Finally, the University of Tartu looked for real world projects for students, and I supplied this project idea.
Four students came (you will see them in the beginnings of the git history) and laid the groundwork for the project.
After the university project ended I started to tinker on the BPMD tool as my hobby project whenever I have had free time.
Additionally, one student continued on the project and wrote his link:https://dspace.ut.ee/items/15c8d161-f7b3-469f-95a8-6ffff2db8a0d[bachelor's thesis] on the topic of layouting data objects, as I was out of ideas how to handle their placement in _half-layers_.
Another student continued on the project as a summer intern within link:cyber.ee[Cybernetica] to implement the groundwork for the PE-BPMD analysis.

After this great kickstart help by link:cyber.ee[Cybernetica], I currently continue to tinker on the BPMD tool during my hobby time, and right now I still enjoy doing so.
