//! This file content was generated by ChatGPT 5.3 (Instant).
//! Comments by a human.

/// Allows iterating forwards or in reverse over an index range, without running into the problem
/// of having different iterator types. In other words, reversed-ness can be controlled during runtime.
pub struct IndexIter {
    cur: isize,
    end: isize,
    /// +1 or -1
    step: isize,
}

impl Iterator for IndexIter {
    type Item = usize;

    fn next(&mut self) -> Option<Self::Item> {
        if self.cur == self.end {
            return None;
        }

        let out = self.cur as usize;
        self.cur += self.step;
        Some(out)
    }
}

pub trait IterIndices {
    fn iter_indices(self, reverse: bool) -> IndexIter;
}

impl IterIndices for usize {
    fn iter_indices(self, reverse: bool) -> IndexIter {
        assert!(
            self <= isize::MAX as usize,
            "There should not be anything as large within this graph layout library"
        );

        let len = self as isize;

        IndexIter {
            cur: if reverse { len - 1 } else { 0 },
            end: if reverse { -1 } else { len },
            step: if reverse { -1 } else { 1 },
        }
    }
}
