name: Rust

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set custom APT sources (new .sources format)
      run: |
        sudo mv /etc/apt/sources.list.d/ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources.backup
        
        sudo tee /etc/apt/sources.list.d/ubuntu.sources <<EOF
        Types: deb
        URIs: http://ee.archive.ubuntu.com/ubuntu/
        Suites: noble noble-updates noble-backports
        Components: main restricted universe multiverse
        Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

        Types: deb
        URIs: http://security.ubuntu.com/ubuntu/
        Suites: noble-security
        Components: main restricted universe multiverse
        Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
        EOF
        
        sudo apt-get update

    - name: Setup CBC
      run: |
        sudo apt-get install coinor-cbc coinor-libcbc-dev

    - name: Setup GCC
      run: |
        sudo apt-get install g++

    - name: Setup Build Essentials
      run: |
        sudo apt-get install build-essential libstdc++-10-dev

    - name: Setup Pkg-config
      run: |
        sudo apt-get install pkg-config

    - name: Run ldconfig
      run: |
        sudo ldconfig

    # - name: Add cbc to cargo.toml
    #   run: |
    #     echo 'cbc-src = "0.2.8"' >> Cargo.toml

    - name: Release
      run: |
        export RUSTFLAGS="-C link-arg=-lstdc++"
        cargo build --release

    - name: Upload release
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: target/release
