name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup cbc solver
      run: |
        sudo apt-get update
        sudo apt-get install  coinor-cbc coinor-libcbc-dev

    - name: Release
      run: cargo build --release

    - name: Upload release
      uses: actions/upload-release-asset@v4
      with:
        name: release
        path: target/release/bpmn-parser
