name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install  coinor-cbc coinor-libcbc-dev
        sudo apt-get install g++
        sudo apt-get install build-essential libstdc++-10-dev
        sudo apt-get install pkg-config

    - name: Add cbc to cargo.toml
      run: |
        echo 'cbc-src = "0.2.8"' >> Cargo.toml

    - name: Release
      run: cargo build --release

    - name: Upload release
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: target/release
