//! Implements a left-right sweep. Modifications for BPMN:
//!  * All nodes of a layer, across all lanes and pools, are considered at the same time, so that
//!    a pair of parallel message flows is correctly influencing the order across lanes.
//!  * To nudge the nodes with message flows and cross-lane sequence flows to the edge of their
//!    lane, additional helper nodes are inserted between the lane nodes and *after every* gateway
//!    branch leading to the respective node, an edge is inserted between the outgoing node and the
//!    artificial node. (what if there are multiple paths to that node?) only if there are multiple
//!    nodes on the whole way (so if at some point there is just one, then there is no point in
//!    nudging in advance of that one "bottleneck".
//!
//! Naaa. New idea: Lane per lane. Then store multiple results, depending on the order. Then stitch
//! lanes together, by checking all combinations for their global crossing counts, take the best one.
use std::collections::HashSet;
use crate::common::graph::{EdgeId, Graph, NodeId, PoolAndLane};
use rustc_hash::FxBuildHasher;
use std::collections::HashMap;

enum Pull {
    UpSf, UpMf, UpDf, DownSf, DownMf,DownDf,
}

// This one could actually be used within NodeId as well. Reduces memory usage significantly, and
// we just won't have 65000 nodes in the diagram. 255 might be a bit small, given that a single
// real node could result in ~5 additional dummy nodes, so would give room for just 42 regular
// nodes. This is quite a lot, but within the boundary of BPMD.
type GeneralIndexType = u16;

struct Slice {
    start: GeneralIndexType,
    end: GeneralIndexType,
}

struct SweepNodeId(usize);

const INCOMING: usize = 0;
const OUTGOING: usize = 1;

struct SweepNode {
    /// To avoid using NodeId (which is 8 bytes), instead index into the respective `Lane::nodes` to
    /// then get the NodeId. Easy :) Goal is to keep the size of `SweepNode` super small.
    in_lane_idx: GeneralIndexType,
    pull: Option<Pull>,
    /// Indexing `EdgeTargets`. Indexed by `INCOMING` or `OUTGOING`.
    ports_start: [GeneralIndexType; 2],
    /// No node will have more than 255 incoming or outgoing edges ...
    /// I really want to keep this
    ports_len: [u8; 2],
    /// Let's pray that there are not 255 nodes in one layer. For the regular use cases of BPMD
    /// this is totally beyond the use case, but for some autogenerated stuff, maybe this could hit?
    layer_position: u8,
}

struct SweepGraph {
    nodes: Vec<SweepNode>,
    /// Indexing `nodes`.
    layers: Vec<Slice>,
    edge_targets : Vec<SweepNodeId>,
}

impl SweepGraph {
    fn new(lane: &Lane, graph: &Graph) -> Self {
let mut result = SweepGraph {
    nodes: Vec::new(),
    layers: Vec::new(),
    edge_targets : Vec::new(),
};

        result
    }
}

#[derive(Hash)]
struct SweepSolutionNode {
    in_lane_idx: GeneralIndexType,
    layer_position: u8,
}

#[derive(Hash)]
struct SingleLaneSweepSolution {
    layers: Vec<SweepSolutionNode>,
}

struct SingleLaneSweepSolutions {
    solutions: HashSet<SingleLaneSweepSolution>,
}

pub fn reduce_all_crossings_sweep(graph: &mut Graph) {
    let mut layers = Layers::new();
    for pool in graph.pools.iter() {
    for lane in pool.lanes.iter() {

    }
    }
    for node in &graph.nodes {
        if node.layer_id.0 + 1 > layers.len() {
            layers.resize(node.layer_id.0 + 1, Layer::new());
        }
        layers[node.layer_id.0].push(node.id);
        for
    }
}

/// Classical left-right sweep.
fn process_sf_and_mf(graph: &mut Graph) {}
