//! Implements a left-right sweep. Modifications for BPMN:
//!  * All nodes of a layer, across all lanes and pools, are considered at the same time, so that
//!    a pair of parallel message flows is correctly influencing the order across lanes.
//!  * To nudge the nodes with message flows and cross-lane sequence flows to the edge of their
//!    lane, additional helper nodes are inserted between the lane nodes and *after every* gateway
//!    branch leading to the respective node, an edge is inserted between the outgoing node and the
//!    artificial node. (what if there are multiple paths to that node?) only if there are multiple
//!    nodes on the whole way (so if at some point there is just one, then there is no point in
//!    nudging in advance of that one "bottleneck".
//!
//! Naaa. New idea: Lane per lane. Then store multiple results, depending on the order. Then stitch
//! lanes together, by checking all combinations for their global crossing counts, take the best one.
use crate::common::edge::Edge;
use crate::common::edge::FlowType;
use crate::common::graph::Coord3;
use crate::common::graph::LaneId;
use crate::common::graph::PoolId;
use crate::common::graph::{EdgeId, Graph, NodeId, PoolAndLane};
use crate::common::lane::Lane;
use crate::common::macros::impl_index;
use crate::common::node::LayerId;
use crate::common::node::Node;
use crate::common::node::NodePhaseAuxData;
use crate::layout::constraint::Above;
use itertools::Itertools;
use proc_macros::{e, n};
use std::cmp::Ordering;
use std::collections::HashMap;
use std::collections::HashSet;
use std::hash::Hash;
use std::hash::Hasher;

mod one_layer;

#[derive(Clone, Debug)]
enum Pull {
    TopWardsSf,
    TopWardsMf,
    TopWardsDf,
    BottomWardsSf,
    BottomWardsMf,
    BottomWardsDf,
}

impl Pull {
    // The bias is so large that it effectively creates a guaranteed layering:
    // Topwards SF pull creates a layer, topwards MF a second one, etc. Within
    // the layer, the nodes are then regularly ordered by their xyz-center.
    fn to_xyz_center_bias(&self, node_count: usize) -> f32 {
        match self {
            Self::TopWardsSf => -3000f32,
            Self::TopWardsMf => -2000f32,
            Self::TopWardsDf => -1000f32,
            Self::BottomWardsDf => node_count as f32 + 1000f32,
            Self::BottomWardsMf => node_count as f32 + 2000f32,
            Self::BottomWardsSf => node_count as f32 + 3000f32,
        }
    }
}

// This one could actually be used within NodeId as well. Reduces memory usage significantly, and
// we just won't have 65000 nodes in the diagram. 255 might be a bit small, given that a single
// real node could result in ~5 additional dummy nodes, so would give room for just 42 regular
// nodes. This is quite a lot, but within the boundary of BPMD.
type GeneralIndexType = u16;

#[derive(Clone)]
struct Slice {
    start: GeneralIndexType,
    end: GeneralIndexType,
}

impl Slice {
    fn as_range(&self) -> std::ops::Range<usize> {
        self.start as usize..self.end as usize
    }
}

#[derive(Debug, Copy, Clone)]
pub(crate) struct SweepNodeId(usize);
impl_index!(SweepNodeId, SweepNode);

const INCOMING: usize = 0;
const OUTGOING: usize = 1;

#[derive(Default, Clone)]
pub(crate) struct SweepNode {
    /// To avoid using NodeId (which is 8 bytes), instead index into the respective `Lane::nodes` to
    /// then get the NodeId. Easy :) Goal is to keep the size of `SweepNode` super small.
    in_lane_idx: GeneralIndexType,
    pull: Option<Pull>,
    /// Indexing `edge_targets`. Indexed by `INCOMING` or `OUTGOING`.
    ports_start: [GeneralIndexType; 2],
    /// No node will have more than 255 incoming or outgoing edges ...
    /// I really want to keep this
    ports_len: [u8; 2],
    /// Let's pray that there are not 255 nodes in one layer. For the regular use cases of BPMD
    /// this is totally beyond the use case, but for some autogenerated stuff, maybe this could hit?
    layer_position: u8,
}

#[derive(Debug)]
pub struct CrossingMinimizationSweepNodeData {
    sweep_node_id: SweepNodeId,
}

#[track_caller]
fn aux(node: &Node) -> SweepNodeId {
    match node.aux {
        NodePhaseAuxData::CrossingMinimizationSweep(ref a) => a.sweep_node_id,
        _ => panic!("{node:#?}"),
    }
}

#[derive(Default, Clone, Hash, PartialEq, Eq)]
struct CrossingCount {
    df_df_crossings: u16,
    mf_df_crossings: u16,
    mf_mf_crossings: u16,
    sf_df_crossings: u16,
    sf_mf_crossings: u16,
    sf_sf_crossings: u16,
}

impl CrossingCount {
    fn count(&mut self, edge1: &Edge, edge2: &Edge) {
        match (&edge1.flow_type, &edge2.flow_type) {
            (FlowType::DataFlow(..), FlowType::DataFlow(..)) => self.df_df_crossings += 1,
            (FlowType::DataFlow(..), FlowType::MessageFlow(..)) => self.mf_df_crossings += 1,
            (FlowType::MessageFlow(..), FlowType::DataFlow(..)) => self.mf_df_crossings += 1,
            (FlowType::MessageFlow(..), FlowType::MessageFlow(..)) => self.mf_mf_crossings += 1,
            (FlowType::SequenceFlow, FlowType::DataFlow(..)) => self.sf_df_crossings += 1,
            (FlowType::SequenceFlow, FlowType::MessageFlow(..)) => self.sf_mf_crossings += 1,
            (FlowType::DataFlow(..), FlowType::SequenceFlow) => self.sf_df_crossings += 1,
            (FlowType::MessageFlow(..), FlowType::SequenceFlow) => self.sf_mf_crossings += 1,
            (FlowType::SequenceFlow, FlowType::SequenceFlow) => self.sf_sf_crossings += 1,
        }
    }

    #[allow(clippy::identity_op)]
    fn weighted_count(&self) -> usize {
        // XXX If you update these numbers, then
        0 // formatting
            + self.sf_sf_crossings as usize * 100
            + self.sf_mf_crossings as usize * 95
            + self.sf_df_crossings as usize * 40
            + self.mf_mf_crossings as usize * 90
            + self.mf_df_crossings as usize * 35
            + self.df_df_crossings as usize * 30
    }
}

impl<'a> std::iter::Sum<&'a CrossingCount> for CrossingCount {
    fn sum<I: Iterator<Item = &'a CrossingCount>>(iter: I) -> Self {
        iter.fold(Self::default(), |acc, x| Self {
            df_df_crossings: acc
                .df_df_crossings
                .checked_add(x.df_df_crossings)
                .expect("overflow in df_df_crossings"),
            mf_df_crossings: acc
                .mf_df_crossings
                .checked_add(x.mf_df_crossings)
                .expect("overflow in mf_df_crossings"),
            mf_mf_crossings: acc
                .mf_mf_crossings
                .checked_add(x.mf_mf_crossings)
                .expect("overflow in mf_mf_crossings"),
            sf_df_crossings: acc
                .sf_df_crossings
                .checked_add(x.sf_df_crossings)
                .expect("overflow in sf_df_crossings"),
            sf_mf_crossings: acc
                .sf_mf_crossings
                .checked_add(x.sf_mf_crossings)
                .expect("overflow in sf_mf_crossings"),
            sf_sf_crossings: acc
                .sf_sf_crossings
                .checked_add(x.sf_sf_crossings)
                .expect("overflow in sf_sf_crossings"),
        })
    }
}

#[derive(Clone, Eq, PartialEq, Hash)]
enum EdgeConnection {
    /// Left loop or a flow which leaves the lane.
    Left,
    /// A straight edge from left to right, staying within the lane.
    Both,
    /// Right loop or a flow which enters the lane.
    Right,
}

#[derive(Clone)]
struct SweepGraph {
    nodes: Vec<SweepNode>,
    /// Indexing `nodes`.
    layers: Vec<Slice>,

    // All edges which are connected to nodes within the lane, so also those which cross lanes.
    // This is used to count the edge crossings between two layers.
    edges: Vec<(EdgeId, EdgeConnection)>,
    /// Indexing `edges`.
    /// `0` are loop edges left of the first layer.
    /// `1` are all edges between first and second layer.
    /// etc
    edge_layers: Vec<Slice>,

    /// `0` are loop edges left of the first layer.
    /// `1` is between first and second layer.
    /// etc
    layers_crossing_count: Vec<CrossingCount>,
    /// Points into `nodes`. Indexed by `SweepNode::ports_start`. Says where edges are going to.
    /// Note: This only includes edges which stay within the lane.
    /// This is used to calculate the ordering number when reordering the non-fixed layer during the
    /// sweep.
    edge_targets: Vec<SweepNodeId>,
}

impl SweepGraph {
    fn new(graph: &mut Graph, pool_lane: PoolAndLane) -> Self {
        let lane = &graph.pools[pool_lane.pool].lanes[pool_lane.lane];
        for (idx, node_id) in lane.nodes.iter().enumerate() {
            n!(*node_id).aux =
                NodePhaseAuxData::CrossingMinimizationSweep(CrossingMinimizationSweepNodeData {
                    sweep_node_id: SweepNodeId(idx),
                });
        }

        let mut result = SweepGraph {
            nodes: Vec::new(),
            layers: Vec::new(),
            edge_targets: Vec::new(),
            edges: Vec::new(),
            edge_layers: Vec::new(),
            layers_crossing_count: Vec::new(),
        };
        let mut layer_it = lane
            .nodes
            .chunk_by(|left_node_id, right_node_id| {
                n!(*left_node_id).layer_id == n!(*right_node_id).layer_id
            })
            .peekable();

        let mut edge_collection = HashSet::new();

        'a: {
            // Go through the left loops.
            let Some(next_layer_nodes) = layer_it.peek() else {
                break 'a;
            };

            for node_id in next_layer_nodes.iter() {
                let node = &n!(*node_id);
                if node.is_snake_edge_bisect_dummy() {
                    continue;
                }
                for incoming in node.incoming.iter() {
                    let edge_connection = if e!(*incoming).stays_within_lane {
                        EdgeConnection::Both
                    } else {
                        EdgeConnection::Right
                    };
                    edge_collection.insert((*incoming, edge_connection));
                }
            }
            result.edges.extend(edge_collection.drain());
            result.edge_layers.push(Slice {
                start: 0,
                end: result.edges.len() as u16,
            });
        }
        let mut i = 0;
        while let Some(chunk) = layer_it.next() {
            result.layers.push(Slice {
                start: result.nodes.len().try_into().expect("too many nodes, oops"),
                end: (result.nodes.len() + chunk.len())
                    .try_into()
                    .expect("too many nodes, oops"),
            });
            // Nodes are first ordered by their location in the file. This kinda brings in the
            // situation that users would expect the same gateway branch order as they have declared
            // it in the `.bpmd` file, if otherwise crossing counts are equal.
            for (initial_position, node_id) in chunk.iter().enumerate() {
                let node = &n!(*node_id);
                let mut sweep_node = SweepNode {
                    in_lane_idx: i,
                    layer_position: initial_position as u8,
                    ..Default::default()
                };
                i += 1;

                // Keep track whether pull is top-wards (<0) or bottom-wards (>0).
                let mut sf_balance = 0i8;
                let mut mf_balance = 0i8;
                let mut df_balance = 0i8;
                {
                    // Do the port traversal once for incoming, ...
                    let ports_start = result.edge_targets.len();
                    for incoming in node.incoming.iter().cloned() {
                        let edge = &e!(incoming);
                        let from = &n!(edge.from);
                        let balance_correction =
                            match from.pool_and_lane().cmp(&node.pool_and_lane()) {
                                Ordering::Equal => {
                                    result.edge_targets.push(aux(from));
                                    continue;
                                }
                                Ordering::Less => -1,
                                Ordering::Greater => 1,
                            };
                        match &edge.flow_type {
                            FlowType::MessageFlow(..) => mf_balance += balance_correction,
                            FlowType::DataFlow(..) => df_balance += balance_correction,
                            FlowType::SequenceFlow => sf_balance += balance_correction,
                        }
                    }
                    let ports_end = result.edge_targets.len();
                    sweep_node.ports_start[INCOMING] = ports_start.try_into().expect("");
                    sweep_node.ports_len[INCOMING] =
                        (ports_end - ports_start).try_into().expect("");
                }
                {
                    // ... and once for outgoing.
                    let ports_start = result.edge_targets.len();
                    for outgoing in node.outgoing.iter().cloned() {
                        let edge = &e!(outgoing);
                        let to = &n!(edge.to);
                        let balance_correction = match to.pool_and_lane().cmp(&node.pool_and_lane())
                        {
                            Ordering::Equal => {
                                result.edge_targets.push(aux(to));
                                continue;
                            }
                            Ordering::Less => -1,
                            Ordering::Greater => 1,
                        };
                        match &edge.flow_type {
                            FlowType::MessageFlow(..) => mf_balance += balance_correction,
                            FlowType::DataFlow(..) => df_balance += balance_correction,
                            FlowType::SequenceFlow => sf_balance += balance_correction,
                        }

                        // Additionally, record all the edges.
                        if !node.is_snake_edge_bisect_dummy() {
                            let edge_connection = if e!(outgoing).stays_within_lane {
                                EdgeConnection::Both
                            } else {
                                EdgeConnection::Left
                            };
                            edge_collection.insert((outgoing, edge_connection));
                        }
                    }
                    let ports_end = result.edge_targets.len();
                    sweep_node.ports_start[OUTGOING] = ports_start.try_into().expect("");
                    sweep_node.ports_len[OUTGOING] =
                        (ports_end - ports_start).try_into().expect("");
                }
                // DFs have the least priority, SFs the most.
                sweep_node.pull = match (sf_balance, mf_balance, df_balance) {
                    (0, 0, 0) => None,
                    (0, 0, _) if df_balance > 0 => Some(Pull::BottomWardsDf),
                    (0, 0, _) => Some(Pull::TopWardsDf),
                    (0, _, _) if mf_balance > 0 => Some(Pull::BottomWardsMf),
                    (0, _, _) => Some(Pull::TopWardsMf),
                    (_, _, _) if sf_balance > 0 => Some(Pull::BottomWardsSf),
                    (_, _, _) => Some(Pull::TopWardsSf),
                };
                result.nodes.push(sweep_node);
            }
            if let Some(next_layer) = layer_it.peek() {
                for node_id in next_layer.iter() {
                    let node = &n!(*node_id);
                    if !node.is_snake_edge_bisect_dummy() {
                        for incoming in node.incoming.iter().cloned() {
                            let edge_connection = if e!(incoming).stays_within_lane {
                                EdgeConnection::Both
                            } else {
                                EdgeConnection::Right
                            };
                            edge_collection.insert((incoming, edge_connection));
                        }
                    }
                }
            }
            let start = result.edges.len();
            let layer_edges_count = edge_collection.len();
            result.edges.extend(edge_collection.drain());
            result.edge_layers.push(Slice {
                start: start as u16,
                end: (start + layer_edges_count) as u16,
            });
        }

        let mut sweep_buffers = SweepBuffers::default();
        assert!(result.edge_layers.len() >= 2);
        for i in 0..(result.layers.len() + 1) {
            let ccount = count_all_crossings_between_two_layers(
                graph,
                lane,
                i.checked_sub(1)
                    .map(|idx| {
                        &result.nodes
                            [result.layers[idx].start as usize..result.layers[idx].end as usize]
                    })
                    .unwrap_or(&[]),
                result
                    .layers
                    .get(i)
                    .map(|range| &result.nodes[range.start as usize..range.end as usize])
                    .unwrap_or(&[]),
                &result.edges
                    [result.edge_layers[i].start as usize..result.edge_layers[i].end as usize],
                &mut sweep_buffers,
                true,
            );
            std::mem::swap(
                &mut sweep_buffers.sort_buffer_1,
                &mut sweep_buffers.sort_buffer_2,
            );
            result.layers_crossing_count.push(ccount);
        }
        result
    }
}

#[derive(PartialEq, Eq, Hash)]
struct SweepSolutionNode {
    in_lane_idx: GeneralIndexType,
    layer_position: u8,
}

#[derive(PartialEq, Eq)]
struct SingleLaneSweepSolution {
    layers: Vec<Vec<SweepSolutionNode>>,
    /// TODO is this useful at all?
    layers_crossing_count: Vec<CrossingCount>,
    /// Sum over `layers_crossing_count`.
    total_crossing_count: CrossingCount,
}

impl SingleLaneSweepSolution {
    fn new(sweep_graph: &SweepGraph) -> Self {
        Self {
            layers: sweep_graph
                .layers
                .iter()
                .map(|layer| {
                    sweep_graph.nodes[layer.start as usize..layer.end as usize]
                        .iter()
                        .map(|sweep_node| SweepSolutionNode {
                            in_lane_idx: sweep_node.in_lane_idx,
                            layer_position: sweep_node.layer_position,
                        })
                        .collect::<Vec<_>>()
                })
                .collect::<Vec<_>>(),
            layers_crossing_count: sweep_graph.layers_crossing_count.to_owned(),
            total_crossing_count: sweep_graph.layers_crossing_count.iter().sum(),
        }
    }
}

/// Manually implement Hash, since only `layers` is required. The crossing count is an optimization,
/// a cache variable.
impl Hash for SingleLaneSweepSolution {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.layers.hash(state);
    }
}

#[derive(Default)]
struct SingleLaneSweepSolutions {
    solutions: HashSet<SingleLaneSweepSolution>,
}

impl SingleLaneSweepSolutions {
    /// Pre: All solutions have the same weighted_count.
    /// If `sweep_graph` has a better weighted_count, then all previous solutions are removed.
    /// If `sweep_graph` has an equal weighted_count, then it is added to the solutions (since it
    /// is a hash-map, a duplicate solution will not change anything)
    /// If `sweep_graph` has a worse weighted_count, then it is ignored.
    fn maybe_add(&mut self, sweep_graph: &SweepGraph) -> bool {
        let Some(a_solution) = self.solutions.iter().next() else {
            self.solutions
                .insert(SingleLaneSweepSolution::new(sweep_graph));
            return true;
        };
        let new_total_crossing_count: CrossingCount =
            sweep_graph.layers_crossing_count.iter().sum();
        match a_solution
            .total_crossing_count
            .weighted_count()
            .cmp(&new_total_crossing_count.weighted_count())
        {
            Ordering::Less => false,
            Ordering::Equal => {
                let previous_count = self.solutions.len();
                self.solutions
                    .insert(SingleLaneSweepSolution::new(sweep_graph));
                self.solutions.len() > previous_count
            }
            Ordering::Greater => {
                self.solutions.clear();
                self.solutions
                    .insert(SingleLaneSweepSolution::new(sweep_graph));
                true
            }
        }
    }
}

type ConstraintMap = HashMap<Coord3, Vec<Above>>;

pub fn reduce_all_crossings_sweep(graph: &mut Graph) {
    let mut constraint_map = ConstraintMap::new();
    for above_constraint in &graph.layout_constraints.above {
        let coord3 = n!(above_constraint.above).coord3();
        if n!(above_constraint.below).coord3() == coord3 {
            constraint_map
                .entry(coord3)
                .or_default()
                .push(above_constraint.clone());
        }
    }
    let mut sweep_buffers = SweepBuffers::default();
    let mut debug_output = String::new();
    for pool_idx in 0..graph.pools.len() {
        for lane_idx in 0..graph.pools[pool_idx].lanes.len() {
            let pool_lane = PoolAndLane {
                pool: PoolId(pool_idx),
                lane: LaneId(lane_idx),
            };
            let sweep_graph = SweepGraph::new(graph, pool_lane);
            left_right_sweeps(
                graph,
                pool_lane,
                &graph.pools[pool_lane.pool].lanes[pool_lane.lane],
                sweep_graph,
                &constraint_map,
                &mut sweep_buffers,
                &mut debug_output,
            );
            debug_output.push_str(", ");
        }
    }
}

fn left_right_sweeps(
    graph: &Graph,
    pool_lane: PoolAndLane,
    lane: &Lane,
    mut sweep_graph: SweepGraph,
    constraint_map: &ConstraintMap,
    sweep_buffers: &mut SweepBuffers,
    debug_output: &mut String,
) {
    let mut best_versions = SingleLaneSweepSolutions::default();
    debug_output.push_str(&format!("p({})/l({}) ", pool_lane.pool.0, pool_lane.lane.0));
    // Pull is taken into account only in the first iterations. If there are pulls from parallel
    // sequence flows into the same direction, this can lead to unpleasant crossings. Hence, let
    // the situation pan out after applying the pull as well.
    for mind_the_pull in [true, false] {
        let mut num_iterations = 0;
        for i in 0..6 {
            num_iterations = i;
            let something_changed = right_sweep(
                graph,
                pool_lane,
                lane,
                &mut sweep_graph,
                &mut best_versions,
                sweep_buffers,
                mind_the_pull,
                constraint_map,
            );
            if !something_changed {
                break;
            }
        }
        debug_output.push_str(&format!("{num_iterations} "));
    }
    //
}

#[derive(Default)]
struct SweepBuffers {
    positions_buffer: Vec<Positions>,
    sort_buffer_1: Vec<(NodeId, /* idx within &[SweepNode] */ usize)>,
    sort_buffer_2: Vec<(NodeId, /* idx within &[SweepNode] */ usize)>,
    /// In the simple case we could just update the `SweepNode::layer_position` as we go through
    /// the nodes in a layer (set to average of incoming). But since we have same-layer edges,
    /// we need to keep the old position value around (for when we encounter the other end of the
    /// edge).
    /// `xyz` since I don't remember whether its barycenter or some average center or median center
    /// or byzantine center or div center or a shopping center or ... I got lost, sorry.
    xyz_center_buffer: Vec<(f32, /* idx within &[SweepNode] */ usize)>,
}

impl SweepBuffers {
    fn new_sweep_direction(&mut self) {
        self.sort_buffer_1.clear();
        self.sort_buffer_2.clear();
        self.xyz_center_buffer.clear();
    }
}

/// Classical left-right sweep.
fn right_sweep(
    graph: &Graph,
    pool_lane: PoolAndLane,
    lane: &Lane,
    sweep_graph: &mut SweepGraph,
    best_versions: &mut SingleLaneSweepSolutions,
    sweep_buffers: &mut SweepBuffers,
    mind_the_pull: bool,
    constraint_map: &ConstraintMap,
) -> bool {
    sweep_buffers.new_sweep_direction();
    let mut something_changed = false;
    for i in 0..sweep_graph.layers.len() {
        let current_position = Coord3 {
            pool_and_lane: pool_lane,
            layer: LayerId(i),
        };
        one_layer::run(
            graph,
            sweep_graph,
            &current_position,
            /* is_right_sweep */ true,
            mind_the_pull,
            constraint_map
                .get(&current_position)
                .map(|v| v.as_slice())
                .unwrap_or_default(),
        );

        let (ccount1, ccount2) = count_crossings_three_layers(
            graph,
            lane,
            i.checked_sub(1)
                .map(|idx| &sweep_graph.nodes[sweep_graph.layers[idx].as_range()])
                .unwrap_or(&[]),
            &sweep_graph.nodes[sweep_graph.layers[i].as_range()],
            sweep_graph
                .layers
                .get(i + 1)
                .map(|range| &sweep_graph.nodes[range.as_range()])
                .unwrap_or(&[]),
            &sweep_graph.edges[sweep_graph.edge_layers[i].as_range()],
            sweep_graph
                .edge_layers
                .get(i + 1)
                .map(|range| &sweep_graph.edges[range.as_range()])
                .unwrap_or(&[]),
            sweep_buffers,
        );
        sweep_graph.layers_crossing_count[i] = ccount1;
        sweep_graph.layers_crossing_count[i + 1] = ccount2;
        something_changed = best_versions.maybe_add(sweep_graph);
    }
    something_changed
}

// Pre: `sort_buffer_1` holds the ordering of `left`.
// Post: `sort_buffer_1` holds the ordering of `middle`.
// TODO add a boolean to reverse this? i.e. Pre holds `right`.
fn count_crossings_three_layers(
    graph: &Graph,
    lane: &Lane,
    left: &[SweepNode],
    middle: &[SweepNode],
    right: &[SweepNode],
    edges_1: &[(EdgeId, EdgeConnection)],
    edges_2: &[(EdgeId, EdgeConnection)],
    sweep_buffers: &mut SweepBuffers,
) -> (CrossingCount, CrossingCount) {
    let left_crossing_count = count_all_crossings_between_two_layers(
        graph,
        lane,
        left,
        middle,
        edges_1,
        sweep_buffers,
        true,
    );
    std::mem::swap(
        // `2` is sorted already (`middle`). Move that into `1`.
        &mut sweep_buffers.sort_buffer_2,
        &mut sweep_buffers.sort_buffer_1,
    );
    let right_crossing_count = count_all_crossings_between_two_layers(
        graph,
        lane,
        middle,
        right,
        edges_2,
        sweep_buffers,
        true,
    );
    // Ensure that the post-condition holds.
    std::mem::swap(
        &mut sweep_buffers.sort_buffer_2,
        &mut sweep_buffers.sort_buffer_1,
    );
    (left_crossing_count, right_crossing_count)
}

fn count_all_crossings_between_two_layers(
    graph: &Graph,
    lane: &Lane,
    prev: &[SweepNode],
    current: &[SweepNode],
    edges: &[(EdgeId, EdgeConnection)],
    sweep_buffers: &mut SweepBuffers,
    keep_left_else_right: bool,
) -> CrossingCount {
    // Thing is, in a sweep we look at overlapping windows of three layers (where the middle one
    // is shuffled). Hence, we can usually reuse the reordering. Should save roughly half of the
    // re-orderings.
    if !keep_left_else_right {
        sweep_buffers.sort_buffer_1.clear();
        for (idx, nprev) in prev.iter().enumerate() {
            sweep_buffers
                .sort_buffer_1
                .push((lane.nodes[nprev.in_lane_idx as usize], idx));
        }
        sweep_buffers
            .sort_buffer_1
            .sort_by_key(|(_, idx)| prev[*idx].layer_position);
    } else {
        sweep_buffers.sort_buffer_2.clear();
        for (idx, ncurrent) in current.iter().enumerate() {
            sweep_buffers
                .sort_buffer_2
                .push((lane.nodes[ncurrent.in_lane_idx as usize], idx));
        }
        sweep_buffers
            .sort_buffer_2
            .sort_by_key(|(_, idx)| current[*idx].layer_position);
    }

    count_all_crossings_between_two_layers_inner(
        edges,
        &mut sweep_buffers.positions_buffer,
        graph,
        &sweep_buffers.sort_buffer_1,
        &sweep_buffers.sort_buffer_2,
    )
}
#[derive(Clone, Copy)]
enum Leaving {
    Upwards,
    Downwards,
}

#[derive(Clone, Copy, PartialEq)]
enum StartOrEnd {
    Start,
    End,
}

struct Positions {
    start: isize,
    end: isize,

    /// `start.min(end)`
    above: isize,
    /// `start.max(end)`
    below: isize,

    // If one end of the edge leaves.
    leaving: Option<(Leaving, StartOrEnd)>,
}

impl Positions {
    // Two loop on the same side. Either both left opened or both right opened.
    fn loop_loop_crossing(left: &Positions, right: &Positions) -> bool {
        let leave_to_same_direction = matches!(
            (left.leaving, right.leaving),
            (Some((Leaving::Upwards, _)), Some((Leaving::Upwards, _)))
                | (Some((Leaving::Downwards, _)), Some((Leaving::Downwards, _)))
        );
        !leave_to_same_direction
            && ((left.above < right.above && right.above < left.below && left.below < right.below)
                || (right.above < left.above
                    && left.above < right.below
                    && right.below < left.below))
    }

    // A loop in `layer` and an edge going from `layer` to `layer + 1`.
    fn loop_non_loop_crossing(left_opened_loop: &Positions, right_straight: &Positions) -> bool {
        let leave_to_same_direction = matches!(
            (left_opened_loop.leaving, right_straight.leaving),
            (
                Some((Leaving::Upwards, _)),
                Some((Leaving::Upwards, StartOrEnd::Start))
            ) | (
                Some((Leaving::Downwards, _)),
                Some((Leaving::Downwards, StartOrEnd::Start))
            )
        );
        !leave_to_same_direction
            && (left_opened_loop.above < right_straight.start
                && right_straight.start < left_opened_loop.below)
    }

    // An edge going from `layer` to `layer + 1`, and a loop in `layer + 1` (on the left side).
    fn non_loop_loop_crossing(left_straight: &Positions, right_opened_loop: &Positions) -> bool {
        let leave_to_same_direction = matches!(
            (left_straight.leaving, right_opened_loop.leaving),
            (
                Some((Leaving::Upwards, StartOrEnd::End)),
                Some((Leaving::Upwards, _))
            ) | (
                Some((Leaving::Downwards, StartOrEnd::End)),
                Some((Leaving::Downwards, _))
            )
        );
        !leave_to_same_direction
            && (right_opened_loop.above < left_straight.end
                && left_straight.end < right_opened_loop.below)
    }

    // Two straight edges between `layer` and `layer + 1`.
    fn non_loop_non_loop_crossing(left: &Positions, right: &Positions) -> bool {
        let some_stays_inside = left.leaving.is_none() || right.leaving.is_none();
        some_stays_inside
            && ((left.start < right.start && left.end > right.end)
                || (left.start > right.start && left.end < right.end))
    }
}

fn get_positions(
    ordering_1: &[(NodeId, usize)],
    ordering_2: &[(NodeId, usize)],
    edge: &Edge,
    graph: &Graph,
) -> Positions {
    let from_node = &n!(edge.from);
    let to_node = &n!(edge.to);
    let mut leaving = None;
    let start = ordering_1
        .iter()
        .find_position(|(node_id, _)| from_node.id == *node_id)
        .map(|tuple| tuple.0 as isize)
        .unwrap_or_else(|| {
            if from_node.pool_and_lane() < to_node.pool_and_lane() {
                leaving = Some((Leaving::Upwards, StartOrEnd::Start));
                isize::MIN
            } else {
                leaving = Some((Leaving::Downwards, StartOrEnd::Start));
                isize::MAX
            }
        });
    let end = ordering_2
        .iter()
        .find_position(|(node_id, _)| to_node.id == *node_id)
        .map(|tuple| tuple.0 as isize)
        .unwrap_or_else(|| {
            // assert: If both sides are leaving, then why is this edge processed in the current
            // lane?
            assert!(leaving.is_none());
            if from_node.pool_and_lane() < to_node.pool_and_lane() {
                leaving = Some((Leaving::Downwards, StartOrEnd::End));
                isize::MAX
            } else {
                leaving = Some((Leaving::Upwards, StartOrEnd::End));
                isize::MIN
            }
        });
    Positions {
        start,
        end,
        above: start.min(end),
        below: start.max(end),
        leaving,
    }
}

fn count_all_crossings_between_two_layers_inner(
    edges: &[(EdgeId, EdgeConnection)],
    positions_buffer: &mut Vec<Positions>,
    graph: &Graph,
    left_ordering: &[(NodeId, /* ignore: */ usize)],
    right_ordering: &[(NodeId, /* ignore: */ usize)],
) -> CrossingCount {
    let mut crossing_count = CrossingCount::default();

    positions_buffer.clear();
    positions_buffer.extend(edges.iter().clone().map(|(edge_id, edge_connection)| {
        match edge_connection {
            EdgeConnection::Left => {
                get_positions(left_ordering, left_ordering, &e!(*edge_id), graph)
            }
            EdgeConnection::Both => {
                get_positions(left_ordering, right_ordering, &e!(*edge_id), graph)
            }
            EdgeConnection::Right => {
                get_positions(right_ordering, right_ordering, &e!(*edge_id), graph)
            }
        }
    }));
    assert_eq!(positions_buffer.len(), edges.len());

    for i in 0..edges.len() {
        for j in (i + 1)..edges.len() {
            count_crossing_one_edge_pair(
                &mut crossing_count,
                edges[i].clone(),
                edges[j].clone(),
                &positions_buffer[i],
                &positions_buffer[j],
                graph,
            );
        }
    }
    crossing_count
}

fn count_crossing_one_edge_pair(
    crossing_count: &mut CrossingCount,
    edge_1: (EdgeId, EdgeConnection),
    edge_2: (EdgeId, EdgeConnection),
    positions_1: &Positions,
    positions_2: &Positions,
    graph: &Graph,
) {
    // TODO this positions_1 and _2 query should be moved one level up and cached. This is itself a
    // linear search.
    let is_crossing = match (edge_1.1, edge_2.1) {
        (EdgeConnection::Left, EdgeConnection::Left) => {
            Positions::loop_loop_crossing(positions_1, positions_2)
        }
        (EdgeConnection::Left, EdgeConnection::Both) => {
            Positions::loop_non_loop_crossing(positions_1, positions_2)
        }
        (EdgeConnection::Left, EdgeConnection::Right) => {
            // Cannot cross
            return;
        }

        (EdgeConnection::Both, EdgeConnection::Left) => {
            Positions::loop_non_loop_crossing(positions_2, positions_1)
        }
        (EdgeConnection::Both, EdgeConnection::Both) => {
            Positions::non_loop_non_loop_crossing(positions_1, positions_2)
        }
        (EdgeConnection::Both, EdgeConnection::Right) => {
            Positions::non_loop_loop_crossing(positions_1, positions_2)
        }

        (EdgeConnection::Right, EdgeConnection::Left) => {
            // Cannot cross
            return;
        }
        (EdgeConnection::Right, EdgeConnection::Both) => {
            Positions::non_loop_loop_crossing(positions_2, positions_1)
        }
        (EdgeConnection::Right, EdgeConnection::Right) => {
            Positions::loop_loop_crossing(positions_1, positions_2)
        }
    };

    if is_crossing {
        crossing_count.count(&e!(edge_1.0), &e!(edge_2.0));
    }
}
