//! Implements a left-right sweep. Modifications for BPMN:
//!  * All nodes of a layer, across all lanes and pools, are considered at the same time, so that
//!    a pair of parallel message flows is correctly influencing the order across lanes.
//!  * To nudge the nodes with message flows and cross-lane sequence flows to the edge of their
//!    lane, additional helper nodes are inserted between the lane nodes and *after every* gateway
//!    branch leading to the respective node, an edge is inserted between the outgoing node and the
//!    artificial node. (what if there are multiple paths to that node?) only if there are multiple
//!    nodes on the whole way (so if at some point there is just one, then there is no point in
//!    nudging in advance of that one "bottleneck".
//!
//! Naaa. New idea: Lane per lane. Then store multiple results, depending on the order. Then stitch
//! lanes together, by checking all combinations for their global crossing counts, take the best one.
use crate::common::edge::Edge;
use crate::common::edge::FlowType;
use crate::common::graph::Coord3;
use crate::common::graph::LaneId;
use crate::common::graph::PoolId;
use crate::common::graph::{EdgeId, Graph, NodeId, PoolAndLane};
use crate::common::lane::Lane;
use crate::common::macros::impl_index;
use crate::common::node::LayerId;
use crate::common::node::Node;
use crate::common::node::NodePhaseAuxData;
use crate::common::vecmap::VecMap;
use crate::common::vecset::VecSet;
use crate::layout::all_crossing_minimization_common::remove_temporarily_added_dummy_nodes_for_edges_within_same_layer;
use crate::layout::all_crossing_minimization_common::temporarily_add_dummy_nodes_for_edges_within_same_layer;
use crate::layout::constraint::Above;
use crate::parser::ParseError;
use itertools::Either;
use itertools::Itertools;
use proc_macros::{e, from, lane, n, to};
use std::cmp::Ordering;
use std::collections::HashMap;
use std::collections::HashSet;
use std::hash::Hash;
use std::hash::Hasher;
use std::rc::Rc;

mod one_layer;

// This one could actually be used within NodeId as well. Reduces memory usage significantly, and
// we just won't have 65000 nodes in the diagram. 255 might be a bit small, given that a single
// real node could result in ~5 additional dummy nodes, so would give room for just 42 regular
// nodes. This is quite a lot, but within the boundary of BPMD.
type GeneralIndexType = u16;

#[derive(Debug, Clone)]
struct Slice {
    start: GeneralIndexType,
    end: GeneralIndexType,
}

impl Slice {
    fn as_range(&self) -> std::ops::Range<usize> {
        self.start as usize..self.end as usize
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub(crate) struct SweepNodeId(usize);
impl_index!(SweepNodeId, SweepNode);

const INCOMING: usize = 0;
const OUTGOING: usize = 1;

#[derive(Debug, Default, Clone)]
pub(crate) struct PullBalance {
    sf_balance: i8,
    mf_balance: i8,
    df_balance: i8,
}

#[derive(Debug, Default, Clone)]
pub(crate) struct SweepNode {
    /// To avoid using NodeId (which is 8 bytes), instead index into the respective `Lane::nodes` to
    /// then get the NodeId. Easy :) Goal is to keep the size of `SweepNode` super small.
    in_lane_idx: GeneralIndexType,
    pull_balance: PullBalance,
    /// Indexing `edge_targets`. Indexed by `INCOMING` or `OUTGOING`.
    ports_start: [GeneralIndexType; 2],
    /// No node will have more than 255 incoming or outgoing edges ...
    /// I really want to keep this
    ports_len: [u8; 2],
    /// Let's pray that there are not 255 nodes in one layer. For the regular use cases of BPMD
    /// this is totally beyond the use case, but for some autogenerated stuff, maybe this could hit?
    layer_position: u8,
}

#[derive(Debug)]
pub struct CrossingMinimizationSweepNodeData {
    sweep_node_id: SweepNodeId,
}

#[track_caller]
fn aux(node: &Node) -> SweepNodeId {
    match node.aux {
        NodePhaseAuxData::CrossingMinimizationSweep(ref a) => a.sweep_node_id,
        _ => panic!("{node:#?}"),
    }
}

#[derive(Debug, Default, Clone, PartialEq, Eq)]
struct CrossingCount {
    df_df_crossings: u16,
    mf_df_crossings: u16,
    mf_mf_crossings: u16,
    sf_df_crossings: u16,
    sf_mf_crossings: u16,
    sf_sf_crossings: u16,
}

impl CrossingCount {
    fn count(&mut self, edge1: &Edge, edge2: &Edge) {
        match (&edge1.flow_type, &edge2.flow_type) {
            (FlowType::DataFlow(..), FlowType::DataFlow(..)) => self.df_df_crossings += 1,
            (FlowType::DataFlow(..), FlowType::MessageFlow(..)) => self.mf_df_crossings += 1,
            (FlowType::MessageFlow(..), FlowType::DataFlow(..)) => self.mf_df_crossings += 1,
            (FlowType::MessageFlow(..), FlowType::MessageFlow(..)) => self.mf_mf_crossings += 1,
            (FlowType::SequenceFlow, FlowType::DataFlow(..)) => self.sf_df_crossings += 1,
            (FlowType::SequenceFlow, FlowType::MessageFlow(..)) => self.sf_mf_crossings += 1,
            (FlowType::DataFlow(..), FlowType::SequenceFlow) => self.sf_df_crossings += 1,
            (FlowType::MessageFlow(..), FlowType::SequenceFlow) => self.sf_mf_crossings += 1,
            (FlowType::SequenceFlow, FlowType::SequenceFlow) => self.sf_sf_crossings += 1,
        }
    }

    #[allow(clippy::identity_op)]
    fn weighted_count(&self) -> usize {
        0 // formatting
            + self.sf_sf_crossings as usize * 100
            + self.sf_mf_crossings as usize * 95
            + self.sf_df_crossings as usize * 40
            + self.mf_mf_crossings as usize * 90
            + self.mf_df_crossings as usize * 35
            + self.df_df_crossings as usize * 30
    }
}

impl<'a> std::iter::Sum<&'a CrossingCount> for CrossingCount {
    fn sum<I: Iterator<Item = &'a CrossingCount>>(iter: I) -> Self {
        iter.fold(Self::default(), |acc, x| Self {
            df_df_crossings: acc
                .df_df_crossings
                .checked_add(x.df_df_crossings)
                .expect("overflow in df_df_crossings"),
            mf_df_crossings: acc
                .mf_df_crossings
                .checked_add(x.mf_df_crossings)
                .expect("overflow in mf_df_crossings"),
            mf_mf_crossings: acc
                .mf_mf_crossings
                .checked_add(x.mf_mf_crossings)
                .expect("overflow in mf_mf_crossings"),
            sf_df_crossings: acc
                .sf_df_crossings
                .checked_add(x.sf_df_crossings)
                .expect("overflow in sf_df_crossings"),
            sf_mf_crossings: acc
                .sf_mf_crossings
                .checked_add(x.sf_mf_crossings)
                .expect("overflow in sf_mf_crossings"),
            sf_sf_crossings: acc
                .sf_sf_crossings
                .checked_add(x.sf_sf_crossings)
                .expect("overflow in sf_sf_crossings"),
        })
    }
}

#[derive(Debug, Clone, Eq, PartialEq, Hash)]
enum EdgeConnection {
    /// Left loop or a flow which leaves the lane.
    Left,
    /// A straight edge from left to right, staying within the lane.
    Both,
    /// Right loop or a flow which enters the lane.
    Right,
}

/// Vertical edge chains are used to build clumps in the layer-reordering. Graph validation in the
/// beginning already ensured that all such connected nodes only form lists (complicated forms like
/// trees or cycles should not be possible).
/// Reminder: Gateways are not connected to `BackEdgeCornerDummy`s in this stage, only after port
/// assignment.
#[derive(Debug, Clone)]
struct VerticalEdgeChain {
    /// One streak of nodes which *must* be ordered as one clump, in the given order, at least in those sweep phases
    /// where we consider vertical edges. The point is that these are connected via vertical edges,
    /// and we want vertical edges to be straight, i.e. there should not be any
    top_to_bottom_node_list: Vec<NodeId>,
    /// In this case there is no Above constraint involved which would break if the order is swapped,
    /// i.e. the algorithm can favor the order which fits more naturally with the barycenters.
    can_be_flipped: bool,
    coord3: Coord3,
}

#[derive(Debug, Clone, Default)]
struct SweepGraph {
    nodes: Vec<SweepNode>,
    /// Indexing `nodes`.
    layers: Vec<Slice>,

    /// All edges. This is used to count the edge crossings between two layers.
    /// TODO does not include snake bisect edges, but those need to be counted as well.
    edges: Vec<(EdgeId, EdgeConnection)>,
    /// Indexing `edges`.
    /// `0` are loop edges left of the first layer.
    /// `1` are all edges between first and second layer.
    /// etc
    edge_layers: Vec<Slice>,

    /// `0` are loop edges left of the first layer.
    /// `1` is between first and second layer.
    /// etc
    layers_crossing_count: Vec<CrossingCount>,
    /// Points into `nodes`. Indexed by `SweepNode::ports_start`. Says where edges are going to.
    /// Note: This only includes edges which stay within the lane.
    /// This is used to calculate the barycenter (and thus ordering number) when reordering the
    /// non-fixed layer during the sweep.
    edge_targets: Vec<(SweepNodeId, EdgeConnection)>,

    /// Required for moving the concerning nodes closer together.
    /// Those are probably only very few, so no need to segment this further into layers.
    /// TODO make use of this.
    /// TODO this excludes those vertical edges which would result in cycles. Must write an analysis
    /// for that, similar to the back edge removal analysis.
    vertical_edge_chains: Rc<Vec<VerticalEdgeChain>>,
}

impl SweepGraph {
    fn new(
        graph: &mut Graph,
        pool_lane: PoolAndLane,
        vertical_edge_chains: Rc<Vec<VerticalEdgeChain>>,
    ) -> Result<Self, ParseError> {
        let lane = &graph.pools[pool_lane.pool].lanes[pool_lane.lane];
        for (idx, node_id) in lane.nodes.iter().enumerate() {
            n!(*node_id).aux =
                NodePhaseAuxData::CrossingMinimizationSweep(CrossingMinimizationSweepNodeData {
                    sweep_node_id: SweepNodeId(idx),
                });
        }

        let mut result = SweepGraph {
            vertical_edge_chains,
            ..Default::default()
        };

        let mut empty_layer_tracker = 0;
        let layer_it = lane
            .nodes
            .chunk_by(|left_node_id, right_node_id| {
                n!(*left_node_id).layer_id == n!(*right_node_id).layer_id
            })
            // Now create empty chunks for the intermediate layers.
            .flat_map(|chunk| {
                let result = (empty_layer_tracker..n!(chunk[0]).layer_id.0)
                    .map(|_| &[][..])
                    .chain(std::iter::once(chunk));
                empty_layer_tracker = n!(chunk[0]).layer_id.0 + 1;
                result
            });

        let mut edge_collection = HashSet::new();

        // We need to prepend a fake layer (i.e. with zero nodes), because we have an initial layer
        // which captures only the right loops.
        let mut layer_it = Some(Default::default() /* meaning &[] */)
            .into_iter()
            .chain(layer_it)
            .peekable();
        let mut in_lane_idx = 0;
        let mut is_initial_fake_layer = true;
        while let Some(chunk) = layer_it.next() {
            if !is_initial_fake_layer {
                result.layers.push(Slice {
                    start: result.nodes.len().try_into().expect("too many nodes, oops"),
                    end: (result.nodes.len() + chunk.len())
                        .try_into()
                        .expect("too many nodes, oops"),
                });
            }

            // Nodes are first ordered by their location in the file. This kinda brings in the
            // situation that users would expect the same gateway branch order as they have declared
            // it in the `.bpmd` file, if otherwise crossing counts are equal.
            for (initial_position, node_id) in chunk.iter().enumerate() {
                assert!(!is_initial_fake_layer);
                let node = &n!(*node_id);
                let mut sweep_node = SweepNode {
                    in_lane_idx,
                    layer_position: initial_position as u8,
                    ..Default::default()
                };
                in_lane_idx += 1;

                {
                    // Record all the edges for crossing counting.
                    if node.is_right_back_edge_corner_dummy() {
                        // Right back edge corner dummies
                        for edge_id in node.incoming.iter() {
                            let edge = &e!(*edge_id);
                            let from = &n!(edge.from);
                            if from.layer_id == node.layer_id {
                                if !edge.stays_within_lane {
                                    edge_collection.insert((*edge_id, EdgeConnection::Left));
                                } else {
                                    // This one is already captured by going through the regular nodes'
                                    // outgoing edges.
                                }
                            } else {
                                // That's the other edge which comes in from the left.
                                assert!(
                                    from.layer_id.0 + 1 == node.layer_id.0,
                                    "edge_id: {}, edge: {:?}, from: {:?}, node: {:?}",
                                    edge_id.0,
                                    edge,
                                    from,
                                    node
                                );
                            }
                        }
                    } else {
                        for edge_id in node.outgoing.iter() {
                            let edge = &e!(*edge_id);
                            let edge_connection = if edge.stays_within_lane
                                && n!(edge.to).layer_id != node.layer_id
                            {
                                EdgeConnection::Both
                            } else {
                                EdgeConnection::Left
                            };
                            edge_collection.insert((*edge_id, edge_connection));
                        }
                    };
                }

                // Keep track whether pull is top-wards (<0) or bottom-wards (>0).
                {
                    // Do the port traversal once for incoming, ...
                    let ports_start = result.edge_targets.len();
                    for edge_id in node.incoming.iter().cloned() {
                        let edge = &e!(edge_id);
                        let from = &n!(edge.from);
                        let balance_correction =
                            match from.pool_and_lane().cmp(&node.pool_and_lane()) {
                                Ordering::Equal => {
                                    let edge_connection = if from.layer_id == node.layer_id {
                                        EdgeConnection::Right
                                    } else {
                                        EdgeConnection::Both
                                    };
                                    result.edge_targets.push((aux(from), edge_connection));
                                    continue;
                                }
                                Ordering::Less => -1,
                                Ordering::Greater => 1,
                            };
                        match &edge.flow_type {
                            FlowType::MessageFlow(..) => {
                                sweep_node.pull_balance.mf_balance += balance_correction
                            }
                            FlowType::DataFlow(..) => {
                                sweep_node.pull_balance.df_balance += balance_correction
                            }
                            FlowType::SequenceFlow => {
                                sweep_node.pull_balance.sf_balance += balance_correction
                            }
                        }
                    }
                    let ports_end = result.edge_targets.len();
                    sweep_node.ports_start[INCOMING] = ports_start.try_into().expect("");
                    sweep_node.ports_len[INCOMING] =
                        (ports_end - ports_start).try_into().expect("");
                }
                {
                    // ... and once for outgoing.
                    let ports_start = result.edge_targets.len();
                    for edge_id in node.outgoing.iter().cloned() {
                        let edge = &e!(edge_id);
                        let to = &n!(edge.to);

                        let balance_correction = match to.pool_and_lane().cmp(&node.pool_and_lane())
                        {
                            Ordering::Equal => {
                                let edge_connection = if to.layer_id == node.layer_id {
                                    EdgeConnection::Left
                                } else {
                                    EdgeConnection::Both
                                };
                                result.edge_targets.push((aux(to), edge_connection));
                                continue;
                            }
                            Ordering::Less => -1,
                            Ordering::Greater => 1,
                        };
                        match &edge.flow_type {
                            FlowType::MessageFlow(..) => {
                                sweep_node.pull_balance.mf_balance += balance_correction
                            }
                            FlowType::DataFlow(..) => {
                                sweep_node.pull_balance.df_balance += balance_correction
                            }
                            FlowType::SequenceFlow => {
                                sweep_node.pull_balance.sf_balance += balance_correction
                            }
                        }
                    }
                    let ports_end = result.edge_targets.len();
                    sweep_node.ports_start[OUTGOING] = ports_start.try_into().expect("");
                    sweep_node.ports_len[OUTGOING] =
                        (ports_end - ports_start).try_into().expect("");
                }
                result.nodes.push(sweep_node);
            }

            if let Some(next_layer) = layer_it.peek() {
                // Peek into the next layer to identify remaining right loops for the crossing counting.
                for node_id in next_layer.iter() {
                    let node = &n!(*node_id);
                    if node.is_left_back_edge_corner_dummy() {
                        // Snake edge bisect dummies are flipped nodes.
                        for edge_id in node.outgoing.iter() {
                            let edge = &e!(*edge_id);
                            let to = &n!(edge.to);
                            if to.layer_id == node.layer_id {
                                if !edge.stays_within_lane {
                                    edge_collection.insert((*edge_id, EdgeConnection::Right));
                                } else {
                                    // This one is already captured by going through the regular nodes'
                                    // incoming edges.
                                }
                            } else {
                                // That's the other edge which comes in from the left.
                                // Just a debug assert as this does not result in panics, just wrong
                                // crossing number counting.
                                debug_assert!(
                                    to.layer_id.0 == node.layer_id.0 + 1,
                                    "edge_id: {}, edge: {:?}, to: {:?}, node: {:?}",
                                    edge_id.0,
                                    edge,
                                    to,
                                    node
                                );
                            }
                        }
                    } else {
                        for edge_id in node.incoming.iter().cloned() {
                            let edge = &e!(edge_id);
                            if !edge.stays_within_lane || n!(edge.from).layer_id == node.layer_id {
                                edge_collection.insert((edge_id, EdgeConnection::Right));
                            } else {
                                // The edge should already be part of edge_collection, since it
                                // should be from one of the outgoing edges.
                                // Just a debug assert as this does not result in panics, just wrong
                                // crossing number counting.
                                debug_assert!(
                                    edge_collection
                                        .iter()
                                        .any(|(existing_id, _)| edge_id == *existing_id),
                                    "node: {node:?},\nedge: {edge:?}\nedge_collection: {edge_collection:?}"
                                );
                            }
                        }
                    }
                }
            }
            let start = result.edges.len();
            let layer_edges_count = edge_collection.len();
            result.edges.extend(edge_collection.drain());
            result.edge_layers.push(Slice {
                start: start as u16,
                end: (start + layer_edges_count) as u16,
            });
            is_initial_fake_layer = false;
        }

        let mut sweep_buffers = SweepBuffers::default();
        assert!(result.edge_layers.len() >= 2);
        for i in 0..(result.layers.len() + 1) {
            let ccount = count_all_crossings_between_two_layers(
                graph,
                lane,
                i.checked_sub(1)
                    .map(|idx| {
                        &result.nodes
                            [result.layers[idx].start as usize..result.layers[idx].end as usize]
                    })
                    .unwrap_or(&[]),
                result
                    .layers
                    .get(i)
                    .map(|range| &result.nodes[range.start as usize..range.end as usize])
                    .unwrap_or(&[]),
                &result.edges
                    [result.edge_layers[i].start as usize..result.edge_layers[i].end as usize],
                &mut sweep_buffers.sort_buffer_0,
                &mut sweep_buffers.sort_buffer_1,
                &mut sweep_buffers.positions_buffer,
            );
            result.layers_crossing_count.push(ccount);
        }
        Ok(result)
    }
}

#[derive(PartialEq, Eq, Hash, Debug)]
struct SweepSolutionNode {
    in_lane_idx: GeneralIndexType,
    layer_position_just_for_sorting: u8,
}

#[derive(PartialEq, Eq)]
struct SingleLaneSweepSolution {
    sorted_layers: Vec</* sorted by layer_position: */ Vec<SweepSolutionNode>>,
    /// TODO is this useful at all?
    layers_crossing_count: Vec<CrossingCount>,
    /// Sum over `layers_crossing_count`.
    total_crossing_count: CrossingCount,
}

impl SingleLaneSweepSolution {
    fn new(sweep_graph: &SweepGraph) -> Self {
        Self {
            sorted_layers: sweep_graph
                .layers
                .iter()
                .map(|layer| {
                    let mut nodes = sweep_graph.nodes[layer.start as usize..layer.end as usize]
                        .iter()
                        .map(|sweep_node| SweepSolutionNode {
                            in_lane_idx: sweep_node.in_lane_idx,
                            layer_position_just_for_sorting: sweep_node.layer_position,
                        })
                        .collect::<Vec<_>>();
                    nodes.sort_unstable_by_key(|n| n.layer_position_just_for_sorting);
                    nodes
                })
                .collect::<Vec<_>>(),
            layers_crossing_count: sweep_graph.layers_crossing_count.to_owned(),
            total_crossing_count: sweep_graph.layers_crossing_count.iter().sum(),
        }
    }
}

/// Manually implement Hash, since only `layers` is required. The crossing count is an optimization,
/// a cache variable.
impl Hash for SingleLaneSweepSolution {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.sorted_layers.hash(state);
    }
}

#[derive(Default)]
struct SingleLaneSweepSolutions {
    solutions: VecSet<SingleLaneSweepSolution>,
}

impl SingleLaneSweepSolutions {
    /// Pre: All solutions have the same weighted_count.
    /// If `sweep_graph` has a better weighted_count, then all previous solutions are removed.
    /// If `sweep_graph` has an equal weighted_count, then it is added to the solutions (since it
    /// is a hash-map, a duplicate solution will not change anything)
    /// If `sweep_graph` has a worse weighted_count, then it is ignored.
    fn maybe_add(&mut self, sweep_graph: &SweepGraph) -> bool {
        let Some(a_solution) = self.solutions.iter().next() else {
            self.solutions
                .insert(SingleLaneSweepSolution::new(sweep_graph));
            return true;
        };
        let new_total_crossing_count: CrossingCount =
            sweep_graph.layers_crossing_count.iter().sum();
        match a_solution
            .total_crossing_count
            .weighted_count()
            .cmp(&new_total_crossing_count.weighted_count())
        {
            Ordering::Less => false,
            Ordering::Equal => {
                let previous_count = self.solutions.len();
                self.solutions
                    .insert(SingleLaneSweepSolution::new(sweep_graph));
                self.solutions.len() > previous_count
            }
            Ordering::Greater => {
                self.solutions.clear();
                self.solutions
                    .insert(SingleLaneSweepSolution::new(sweep_graph));
                true
            }
        }
    }
}

type ConstraintMap = HashMap<Coord3, Vec<Above>>;

pub fn reduce_all_crossings_sweep(graph: &mut Graph) -> Result<(), ParseError> {
    let undo = temporarily_add_dummy_nodes_for_edges_within_same_layer(graph);
    let vertical_edge_chains = calculate_vertical_edge_chains(graph)?;
    let mut constraint_map = ConstraintMap::new();
    for above_constraint in &graph.layout_constraints.above {
        let coord3 = n!(above_constraint.above).coord3();
        if n!(above_constraint.below).coord3() == coord3 {
            constraint_map
                .entry(coord3)
                .or_default()
                .push(above_constraint.clone());
        }
    }
    let mut sweep_buffers = SweepBuffers::default();
    let mut debug_output = String::new();
    let mut all_best_versions = Vec::new();
    for pool_idx in 0..graph.pools.len() {
        for lane_idx in 0..graph.pools[pool_idx].lanes.len() {
            let pool_lane = PoolAndLane {
                pool: PoolId(pool_idx),
                lane: LaneId(lane_idx),
            };
            let sweep_graph = SweepGraph::new(graph, pool_lane, vertical_edge_chains.clone())?;
            let best_versions = left_right_sweeps(
                graph,
                pool_lane,
                sweep_graph,
                &constraint_map,
                &mut sweep_buffers,
                &mut debug_output,
            );
            debug_output.push_str(", ");
            all_best_versions.push(best_versions);
        }
    }
    println!("{debug_output}");

    // TODO at this location, if there is a lane with multiple best solutions, one would need to
    // test them all out.
    {}

    let mut best_it = all_best_versions.iter();
    for (pool_idx, pool) in graph.pools.iter().enumerate() {
        for (lane_idx, lane) in pool.lanes.iter().enumerate() {
            let best_solutions = best_it.next().unwrap();
            if best_solutions.solutions.len() > 1 {
                println!(
                    "p({})/l({}) has {} solutions, taking some random one",
                    pool_idx,
                    lane_idx,
                    best_solutions.solutions.len()
                );
            }
            let solution = best_solutions.solutions.iter().next().unwrap();
            for sorted_layer in &solution.sorted_layers {
                sorted_layer.array_windows().for_each(|[above, below]| {
                    let above_node_id = lane.nodes[above.in_lane_idx as usize];
                    let below_node_id = lane.nodes[below.in_lane_idx as usize];
                    graph.nodes[above_node_id].node_below_in_same_lane = Some(below_node_id);
                    graph.nodes[below_node_id].node_above_in_same_lane = Some(above_node_id);
                });
            }
        }
    }
    remove_temporarily_added_dummy_nodes_for_edges_within_same_layer(graph, undo);
    Ok(())
}

fn left_right_sweeps(
    graph: &Graph,
    pool_lane: PoolAndLane,
    mut sweep_graph: SweepGraph,
    constraint_map: &ConstraintMap,
    sweep_buffers: &mut SweepBuffers,
    debug_output: &mut String,
) -> SingleLaneSweepSolutions {
    let mut best_versions = SingleLaneSweepSolutions::default();
    debug_output.push_str(&format!("p({})/l({}) ", pool_lane.pool.0, pool_lane.lane.0));
    // Pull is taken into account only in the first iterations. If there are pulls from parallel
    // sequence flows into the same direction, this can lead to unpleasant crossings. Hence, let
    // the situation pan out after applying the pull as well.
    let mut one_right_sweep_is_done = false;

    for (mind_the_pull, max_iter) in [(true, 6), (false, 6)] {
        let mut num_iterations = 0;
        for i in 0..max_iter {
            num_iterations = i;
            let mut something_changed = false;
            for is_right_sweep in [true, false] {
                let something_changed_local = one_direction_sweep(
                    graph,
                    pool_lane,
                    &mut sweep_graph,
                    &mut best_versions,
                    sweep_buffers,
                    mind_the_pull,
                    is_right_sweep,
                    constraint_map,
                    one_right_sweep_is_done,
                );
                if best_versions
                    .solutions
                    .iter()
                    .next()
                    .is_some_and(|v| v.total_crossing_count.weighted_count() == 0)
                {
                    // The current best version already has 0 crossings. There is no need
                    // to continue searching for something even better, as that does not exist.
                    return best_versions;
                }
                one_right_sweep_is_done = true;
                // Don't inline! Otherwise, it would short-circuit. But we want to do the full
                // right-left sweep.
                something_changed = something_changed || something_changed_local;
            }
            if !something_changed {
                break;
            }
        }
        debug_output.push_str(&format!("{num_iterations} "));
    }
    //
    best_versions
}

#[derive(Default)]
struct SweepBuffers {
    positions_buffer: Vec<Positions>,
    sort_buffer_0: Vec<(NodeId, /* idx within &[SweepNode] */ usize)>,
    sort_buffer_1: Vec<(NodeId, /* idx within &[SweepNode] */ usize)>,
    sort_buffer_2: Vec<(NodeId, /* idx within &[SweepNode] */ usize)>,
    /// In the simple case we could just update the `SweepNode::layer_position` as we go through
    /// the nodes in a layer (set to average of incoming). But since we have same-layer edges,
    /// we need to keep the old position value around (for when we encounter the other end of the
    /// edge).
    /// `xyz` since I don't remember whether its barycenter or some average center or median center
    /// or byzantine center or div center or a shopping center or ... I got lost, sorry.
    xyz_center_buffer: Vec<(f32, /* idx within &[SweepNode] */ usize)>,
}

impl SweepBuffers {
    fn new_sweep_direction(&mut self) {
        self.sort_buffer_0.clear();
        self.sort_buffer_1.clear();
        self.sort_buffer_2.clear();
        self.xyz_center_buffer.clear();
    }
}

/// Classical left-right sweep.
fn one_direction_sweep(
    graph: &Graph,
    pool_lane: PoolAndLane,
    sweep_graph: &mut SweepGraph,
    best_versions: &mut SingleLaneSweepSolutions,
    sweep_buffers: &mut SweepBuffers,
    mind_the_pull: bool,
    is_right_sweep: bool,
    constraint_map: &ConstraintMap,
    one_right_sweep_is_done: bool,
) -> bool {
    let mut something_changed = false;
    let lane = &lane!(pool_lane);
    let layer_idx_iter = if is_right_sweep {
        Either::Left(0..sweep_graph.layers.len())
    } else {
        Either::Right((0..sweep_graph.layers.len()).rev())
    };
    sweep_buffers.new_sweep_direction();
    for i in layer_idx_iter {
        let current_position = Coord3 {
            pool_and_lane: pool_lane,
            layer: LayerId(i),
        };
        one_layer::run(
            graph,
            sweep_graph,
            &current_position,
            is_right_sweep,
            mind_the_pull,
            constraint_map
                .get(&current_position)
                .map(|v| v.as_slice())
                .unwrap_or_default(),
        );
        let (ccount1, ccount2) = count_crossings_three_layers(
            graph,
            lane,
            i.checked_sub(1)
                .map(|idx| &sweep_graph.nodes[sweep_graph.layers[idx].as_range()])
                .unwrap_or(&[]),
            &sweep_graph.nodes[sweep_graph.layers[i].as_range()],
            sweep_graph
                .layers
                .get(i + 1)
                .map(|range| &sweep_graph.nodes[range.as_range()])
                .unwrap_or(&[]),
            &sweep_graph.edges[sweep_graph.edge_layers[i].as_range()],
            sweep_graph
                .edge_layers
                .get(i + 1)
                .map(|range| &sweep_graph.edges[range.as_range()])
                .unwrap_or(&[]),
            sweep_buffers,
        );
        sweep_graph.layers_crossing_count[i] = ccount1;
        sweep_graph.layers_crossing_count[i + 1] = ccount2;
        if one_right_sweep_is_done {
            // With constraints, we need to ensure that we get at least once through the whole
            // graph to satisfy all constraints. The current implementation is too conservative.
            // We could check at each step whether there are more unsatisfied constraints left.
            // But I hope that this conservative version is sufficient in practice.
            something_changed = best_versions.maybe_add(sweep_graph);
        }
    }
    if !one_right_sweep_is_done {
        // At the end of the first sweep we can for sure add the current result as a best version.
        something_changed = best_versions.maybe_add(sweep_graph);
    }
    something_changed
}

// Pre: `sort_buffer_1` holds the ordering of `left`.
// Post: `sort_buffer_1` holds the ordering of `middle`.
// TODO add a boolean to reverse this? i.e. Pre holds `right`.
fn count_crossings_three_layers(
    graph: &Graph,
    lane: &Lane,
    left: &[SweepNode],
    middle: &[SweepNode],
    right: &[SweepNode],
    edges_1: &[(EdgeId, EdgeConnection)],
    edges_2: &[(EdgeId, EdgeConnection)],
    sweep_buffers: &mut SweepBuffers,
) -> (CrossingCount, CrossingCount) {
    let left_crossing_count = count_all_crossings_between_two_layers(
        graph,
        lane,
        left,
        middle,
        edges_1,
        &mut sweep_buffers.sort_buffer_0,
        &mut sweep_buffers.sort_buffer_1,
        &mut sweep_buffers.positions_buffer,
    );
    let right_crossing_count = count_all_crossings_between_two_layers(
        graph,
        lane,
        middle,
        right,
        edges_2,
        &mut sweep_buffers.sort_buffer_0,
        &mut sweep_buffers.sort_buffer_1,
        &mut sweep_buffers.positions_buffer,
    );
    (left_crossing_count, right_crossing_count)
}

fn count_all_crossings_between_two_layers(
    graph: &Graph,
    lane: &Lane,
    prev: &[SweepNode],
    current: &[SweepNode],
    edges: &[(EdgeId, EdgeConnection)],
    // TODO there can be a bit of optimization here to avoid duplicate sorting. But it was too much
    // fiddling for me at the moment.
    sort_buffer_prev: &mut Vec<(NodeId, /* idx within &[SweepNode] */ usize)>,
    sort_buffer_current: &mut Vec<(NodeId, /* idx within &[SweepNode] */ usize)>,
    positions_buffer: &mut Vec<Positions>,
) -> CrossingCount {
    sort_buffer_prev.clear();
    for (idx, nprev) in prev.iter().enumerate() {
        sort_buffer_prev.push((lane.nodes[nprev.in_lane_idx as usize], idx));
    }
    sort_buffer_prev.sort_by_key(|(_, idx)| prev[*idx].layer_position);

    sort_buffer_current.clear();
    for (idx, ncurrent) in current.iter().enumerate() {
        sort_buffer_current.push((lane.nodes[ncurrent.in_lane_idx as usize], idx));
    }
    sort_buffer_current.sort_by_key(|(_, idx)| current[*idx].layer_position);

    count_all_crossings_between_two_layers_inner(
        edges,
        positions_buffer,
        graph,
        sort_buffer_prev,
        sort_buffer_current,
    )
}
#[derive(Clone, Copy)]
enum Leaving {
    Upwards,
    Downwards,
}

#[derive(Clone, Copy, PartialEq)]
enum StartOrEnd {
    Start,
    End,
}

struct Positions {
    start: isize,
    end: isize,

    /// `start.min(end)`
    above: isize,
    /// `start.max(end)`
    below: isize,

    // If one end of the edge leaves.
    leaving: Option<(Leaving, StartOrEnd)>,
}

impl Positions {
    // Two loop on the same side. Either both left opened or both right opened.
    fn loop_loop_crossing(left: &Positions, right: &Positions) -> bool {
        let leave_to_same_direction = matches!(
            (left.leaving, right.leaving),
            (Some((Leaving::Upwards, _)), Some((Leaving::Upwards, _)))
                | (Some((Leaving::Downwards, _)), Some((Leaving::Downwards, _)))
        );
        !leave_to_same_direction
            && ((left.above < right.above && right.above < left.below && left.below < right.below)
                || (right.above < left.above
                    && left.above < right.below
                    && right.below < left.below))
    }

    // A loop in `layer` and an edge going from `layer` to `layer + 1`.
    fn loop_non_loop_crossing(left_opened_loop: &Positions, right_straight: &Positions) -> bool {
        let leave_to_same_direction = matches!(
            (left_opened_loop.leaving, right_straight.leaving),
            (
                Some((Leaving::Upwards, _)),
                Some((Leaving::Upwards, StartOrEnd::Start))
            ) | (
                Some((Leaving::Downwards, _)),
                Some((Leaving::Downwards, StartOrEnd::Start))
            )
        );
        !leave_to_same_direction
            && (left_opened_loop.above < right_straight.start
                && right_straight.start < left_opened_loop.below)
    }

    // An edge going from `layer` to `layer + 1`, and a loop in `layer + 1` (on the left side).
    fn non_loop_loop_crossing(left_straight: &Positions, right_opened_loop: &Positions) -> bool {
        let leave_to_same_direction = matches!(
            (left_straight.leaving, right_opened_loop.leaving),
            (
                Some((Leaving::Upwards, StartOrEnd::End)),
                Some((Leaving::Upwards, _))
            ) | (
                Some((Leaving::Downwards, StartOrEnd::End)),
                Some((Leaving::Downwards, _))
            )
        );
        !leave_to_same_direction
            && (right_opened_loop.above < left_straight.end
                && left_straight.end < right_opened_loop.below)
    }

    // Two straight edges between `layer` and `layer + 1`.
    fn non_loop_non_loop_crossing(left: &Positions, right: &Positions) -> bool {
        let some_stays_inside = left.leaving.is_none() || right.leaving.is_none();
        some_stays_inside
            && ((left.start < right.start && left.end > right.end)
                || (left.start > right.start && left.end < right.end))
    }
}

fn get_positions(
    ordering_1: &[(NodeId, usize)],
    ordering_2: &[(NodeId, usize)],
    edge: &Edge,
    graph: &Graph,
) -> Positions {
    let from_node = &n!(edge.from);
    let to_node = &n!(edge.to);
    let mut leaving = None;
    let start = ordering_1
        .iter()
        .find_position(|(node_id, _)| from_node.id == *node_id)
        .map(|tuple| tuple.0 as isize)
        .unwrap_or_else(|| {
            if from_node.pool_and_lane() < to_node.pool_and_lane() {
                leaving = Some((Leaving::Upwards, StartOrEnd::Start));
                isize::MIN
            } else {
                leaving = Some((Leaving::Downwards, StartOrEnd::Start));
                isize::MAX
            }
        });
    let end = ordering_2
        .iter()
        .find_position(|(node_id, _)| to_node.id == *node_id)
        .map(|tuple| tuple.0 as isize)
        .unwrap_or_else(|| {
            // assert: If both sides are leaving, then why is this edge processed in the current
            // lane?
            assert!(
                leaving.is_none(),
                "from_node: {from_node:?},\nto_node: {to_node:?}\nordering_1: {ordering_1:?},\nordering_2: {ordering_2:?}"
            );
            if from_node.pool_and_lane() < to_node.pool_and_lane() {
                leaving = Some((Leaving::Downwards, StartOrEnd::End));
                isize::MAX
            } else {
                leaving = Some((Leaving::Upwards, StartOrEnd::End));
                isize::MIN
            }
        });
    Positions {
        start,
        end,
        above: start.min(end),
        below: start.max(end),
        leaving,
    }
}

fn count_all_crossings_between_two_layers_inner(
    edges: &[(EdgeId, EdgeConnection)],
    positions_buffer: &mut Vec<Positions>,
    graph: &Graph,
    left_ordering: &[(NodeId, /* ignore: */ usize)],
    right_ordering: &[(NodeId, /* ignore: */ usize)],
) -> CrossingCount {
    let mut crossing_count = CrossingCount::default();

    positions_buffer.clear();
    positions_buffer.extend(edges.iter().clone().map(|(edge_id, edge_connection)| {
        match edge_connection {
            EdgeConnection::Left => {
                get_positions(left_ordering, left_ordering, &e!(*edge_id), graph)
            }
            EdgeConnection::Both => {
                get_positions(left_ordering, right_ordering, &e!(*edge_id), graph)
            }
            EdgeConnection::Right => {
                get_positions(right_ordering, right_ordering, &e!(*edge_id), graph)
            }
        }
    }));
    assert_eq!(positions_buffer.len(), edges.len());

    for i in 0..edges.len() {
        for j in (i + 1)..edges.len() {
            count_crossing_one_edge_pair(
                &mut crossing_count,
                edges[i].clone(),
                edges[j].clone(),
                &positions_buffer[i],
                &positions_buffer[j],
                graph,
            );
        }
    }
    crossing_count
}

fn count_crossing_one_edge_pair(
    crossing_count: &mut CrossingCount,
    edge_1: (EdgeId, EdgeConnection),
    edge_2: (EdgeId, EdgeConnection),
    positions_1: &Positions,
    positions_2: &Positions,
    graph: &Graph,
) {
    // TODO this positions_1 and _2 query should be moved one level up and cached. This is itself a
    // linear search.
    let is_crossing = match (edge_1.1, edge_2.1) {
        (EdgeConnection::Left, EdgeConnection::Left) => {
            Positions::loop_loop_crossing(positions_1, positions_2)
        }
        (EdgeConnection::Left, EdgeConnection::Both) => {
            Positions::loop_non_loop_crossing(positions_1, positions_2)
        }
        (EdgeConnection::Left, EdgeConnection::Right) => {
            // Cannot cross
            return;
        }

        (EdgeConnection::Both, EdgeConnection::Left) => {
            Positions::loop_non_loop_crossing(positions_2, positions_1)
        }
        (EdgeConnection::Both, EdgeConnection::Both) => {
            Positions::non_loop_non_loop_crossing(positions_1, positions_2)
        }
        (EdgeConnection::Both, EdgeConnection::Right) => {
            Positions::non_loop_loop_crossing(positions_1, positions_2)
        }

        (EdgeConnection::Right, EdgeConnection::Left) => {
            // Cannot cross
            return;
        }
        (EdgeConnection::Right, EdgeConnection::Both) => {
            Positions::non_loop_loop_crossing(positions_2, positions_1)
        }
        (EdgeConnection::Right, EdgeConnection::Right) => {
            Positions::loop_loop_crossing(positions_1, positions_2)
        }
    };

    if is_crossing {
        crossing_count.count(&e!(edge_1.0), &e!(edge_2.0));
    }
}

/// See documentation for `VerticalEdgeChain`.
fn calculate_vertical_edge_chains(graph: &Graph) -> Result<Rc<Vec<VerticalEdgeChain>>, ParseError> {
    /// Chains shall only be of list structure, and not form a cycle.
    struct IllegalChainSituation;

    // TODO maybe this function can be simplified, since we can simply follow `is_vertical` edges
    // instead of looking for `Above` constraints.
    fn next_chain_link<'a>(
        node: &Node,
        previous_node_id: Option<NodeId>,
        current_chain: &[&Node],
        above_constraints_to_follow: &mut Vec<Above>,
        graph: &'a Graph,
    ) -> Result<Option<&'a Node>, IllegalChainSituation> {
        let mut it = node
            .incoming
            .iter()
            .map(|edge_id| &from!(*edge_id))
            .chain(node.outgoing.iter().map(|edge_id| &to!(*edge_id)))
            .filter(|next_node| {
                Some(next_node.id) != previous_node_id && next_node.coord3() == node.coord3()
            });
        if let Some(above) = graph
            .layout_constraints
            .above
            .iter()
            .find(|above| above.above == node.id || above.below == node.id)
        {
            above_constraints_to_follow.push(above.clone());
        }
        match (it.next(), it.next()) {
            (None, None) => Ok(None),
            (Some(next_node), None)
                // Not a loop.
                if !current_chain.iter().any(|prev| std::ptr::eq(*prev, next_node)) =>
            {
                Ok(Some(next_node))
            }
            _ => Err(IllegalChainSituation),
        }
    }

    fn follow_above_constraints(
        towards_below: bool,
        next_constrained_node: NodeId,
        constraints: &[Above],
        initial_chain_pos: usize,
        chain: &[&Node],
        mut left_the_chain: bool,
        forwards_is_legal: &mut bool,
        backwards_is_legal: &mut bool,
    ) -> Result<(), ParseError> {
        if towards_below {
            if let Some(position) = chain
                .iter()
                .position(|node| node.id == next_constrained_node)
            {
                if left_the_chain {
                    // Problem is that the vertical edge chain is interrupted by some other node
                    // which needs to be fitted in between. This is forbidden right now.
                    let mut err = vec![(
                        "A vertical edge chain is broken up by `above` place constraints (an unrelated node would be forced between to connected nodes on the same layer). This is forbidden as it would result in an S shaped vertical edge, hurting readability (if you disagree, please show me your situation). This is the first node of the chain of vertically connected nodes:".to_string(),
                        chain[0].tc(),
                    )];
                    for node in chain.iter().skip(1) {
                        err.push(("This is the next node".to_string(), node.tc()));
                    }
                    return Err(err);
                }
                // There is an above chain
                if position > initial_chain_pos {
                    *backwards_is_legal = false;
                } else {
                    // Otherwise, we have an Above loop, but that should have been detected earlier.
                    assert!(position < initial_chain_pos);
                    *forwards_is_legal = false;
                }
                // Found a streak, so finish. We look for more streaks in later outer
                // iterations, no need to continue at this point. It's all a bit suboptimal,
                // but the involved amount of nodes, constraints etc is so small that it should
                // not matter.
                return Ok(());
            } else {
                left_the_chain = true;
            }
            for Above { below, .. } in constraints
                .iter()
                .filter(|above| above.above == next_constrained_node)
            {
                follow_above_constraints(
                    towards_below,
                    *below,
                    constraints,
                    initial_chain_pos,
                    chain,
                    left_the_chain,
                    forwards_is_legal,
                    backwards_is_legal,
                )?;
                if !*forwards_is_legal && !*backwards_is_legal {
                    // This error is handled outside.
                    return Ok(());
                }
            }
        } else {
            if let Some(position) = chain
                .iter()
                .position(|node| node.id == next_constrained_node)
            {
                if left_the_chain {
                    // Problem is that the vertical edge chain is interrupted by some other node
                    // which needs to be fitted in between. This is forbidden right now.
                    let mut err = vec![(
                        "A vertical edge chain is broken up by `above` place constraints (an unrelated node would be forced between to connected nodes on the same layer). This is forbidden as it would result in an S shaped vertical edge, hurting readability (if you disagree, please show me your situation). This is the first node of the chain of vertically connected nodes:".to_string(),
                        chain[0].tc(),
                    )];
                    for node in chain.iter().skip(1) {
                        err.push(("This is the next node".to_string(), node.tc()));
                    }
                    return Err(err);
                }
                // There is an above chain
                if position > initial_chain_pos {
                    *forwards_is_legal = false;
                } else {
                    // Otherwise, we have an Above loop, but that should have been detected earlier.
                    assert!(position < initial_chain_pos);
                    *backwards_is_legal = false;
                }
                // Found a streak, so finish. We look for more streaks in later outer
                // iterations, no need to continue at this point. It's all a bit suboptimal,
                // but the involved amount of nodes, constraints etc is so small that it should
                // not matter.
                return Ok(());
            } else {
                left_the_chain = true;
            }
            for Above { above, .. } in constraints
                .iter()
                .filter(|above| above.below == next_constrained_node)
            {
                follow_above_constraints(
                    towards_below,
                    *above,
                    constraints,
                    initial_chain_pos,
                    chain,
                    left_the_chain,
                    forwards_is_legal,
                    backwards_is_legal,
                )?;
                if !*forwards_is_legal && !*backwards_is_legal {
                    // This error is handled outside.
                    return Ok(());
                }
            }
        }
        Ok(())
    }

    let mut vertical_edge_chains = Vec::<VerticalEdgeChain>::new();
    let mut above_constraints_to_follow = Vec::<Above>::new();
    'outer: for node in &graph.nodes {
        if vertical_edge_chains
            .iter()
            .any(|chain| chain.top_to_bottom_node_list.contains(&node.id))
        {
            // This node is already part of a valid chain. So don't repeat work.
            // (it can be part of an illegal chain, and since those are not recorded, in that case
            // work would be repeated.)
            continue 'outer;
        }
        above_constraints_to_follow.clear();
        let mut previous_node_id = None;
        let mut chain = Vec::new();
        let mut current_node = node;
        'inner: loop {
            chain.push(current_node);
            let next = match next_chain_link(
                current_node,
                previous_node_id,
                &chain,
                &mut above_constraints_to_follow,
                graph,
            ) {
                Err(IllegalChainSituation) => {
                    // This captures the situation in the first iteration (`previous_node_id ==
                    // None`) that the node is not a start or end of the chain, but in the middle.
                    // Those are also just ignored, we want to start from some end.
                    // But also captures an illegal branching situation, or cycle detection, in
                    // the middle of traversing the (potential) chain.
                    continue 'outer;
                }
                Ok(None) => break 'inner,
                Ok(Some(next)) => next,
            };
            previous_node_id = Some(current_node.id);
            current_node = next;
        }
        if chain.len() < 2 {
            // That's not a chain, goddammit! It's just a link, wake up!
            continue 'outer;
        }

        let mut forwards_is_legal = true;
        let mut backwards_is_legal = true;
        for above in above_constraints_to_follow.iter().cloned() {
            if let Some(initial_chain_pos) = chain.iter().position(|node| node.id == above.above) {
                follow_above_constraints(
                    true,
                    above.below,
                    &graph.layout_constraints.above,
                    initial_chain_pos,
                    &chain,
                    false,
                    &mut forwards_is_legal,
                    &mut backwards_is_legal,
                )?;
                if !forwards_is_legal && !backwards_is_legal {
                    let mut err = vec![(
                        "A vertical edge chain could not be laid out straight in one direction or the other, due to conflicting `above` place constraints.. This is forbidden as it would result in an S shaped vertical edge, hurting readability (if you disagree, please show me your situation). This is the first node of the chain of vertically connected nodes:".to_string(),
                        chain[0].tc(),
                    )];
                    for node in chain.iter().skip(1) {
                        err.push(("This is the next node".to_string(), node.tc()));
                    }
                    return Err(err);
                }
            }
            if let Some(initial_chain_pos) = chain.iter().position(|node| node.id == above.below) {
                follow_above_constraints(
                    false,
                    above.above,
                    &graph.layout_constraints.above,
                    initial_chain_pos,
                    &chain,
                    false,
                    &mut forwards_is_legal,
                    &mut backwards_is_legal,
                )?;
                if !forwards_is_legal && !backwards_is_legal {
                    let mut err = vec![(
                        "A vertical edge chain could not be laid out straight in one direction or the other, due to conflicting `above` place constraints.. This is forbidden as it would result in an S shaped vertical edge, hurting readability (if you disagree, please show me your situation). This is the first node of the chain of vertically connected nodes:".to_string(),
                        chain[0].tc(),
                    )];
                    for node in chain.iter().skip(1) {
                        err.push(("This is the next node".to_string(), node.tc()));
                    }
                    return Err(err);
                }
            }
        }
        assert!(forwards_is_legal || backwards_is_legal);
        if !forwards_is_legal {
            chain.reverse();
            std::mem::swap(&mut forwards_is_legal, &mut backwards_is_legal);
        }
        vertical_edge_chains.push(VerticalEdgeChain {
            top_to_bottom_node_list: chain.iter().map(|node| node.id).collect(),
            can_be_flipped: backwards_is_legal,
            coord3: node.coord3(),
        });
    }
    Ok(Rc::new(vertical_edge_chains))
}
